services:
  - type: web
    name: gallery-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: PORT
        value: 10000
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1
