services:
  - type: web
    name: flask
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m flask run --host=0.0.0.0 --port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
